services:
    db:
        image: &db-image mysql:8
        restart: unless-stopped
        container_name: db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        ports:
            - 3306:3306
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - db-network
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u ${DB_USERNAME} --password=${DB_PASSWORD}
            interval: 5s
            timeout: 10s
            retries: 20

    db-test:
        image: *db-image
        container_name: db-test
        command: --max-connections=250
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: test_db
            MYSQL_USER: test_user
            MYSQL_PASSWORD: test_user_password
            MYSQL_ROOT_PASSWORD: root_password
        networks:
            - db-network

    app:
        &app
        build:
            context: ./
            dockerfile: docker/php/Dockerfile-dev
        restart: unless-stopped
        container_name: app
        environment:
            COMMAND: php artisan octane:start --watch --host=0.0.0.0 --port=8000 --verbose
            PROCESS: app
            XDEBUG_MODE: debug,coverage
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_healthy
        volumes:
            - ./:/var/www
            - app_composer_data:/.composer
            - app_npm_data:/.npm
        ports:
            - "5173:5173"
        networks:
            - db-network
            - webserver-network
            - redis-network
        healthcheck:
            test: curl -s http://localhost:8000/up >/dev/null || exit 1
            interval: 5s
            timeout: 10s
            retries: 20

    workers:
        <<: *app
        container_name: worker
        environment:
            COMMAND: php artisan queue:work
            PROCESS: worker
        ports: []
        networks:
            - db-network
            - redis-network

    schedule:
        <<: *app
        container_name: schedule
        environment:
            COMMAND: supercronic -quiet /var/www/docker/php/schedule/schedule
            PROCESS: schedule
        networks:
            - db-network
            - redis-network
        ports: []
        healthcheck:
            test: supercronic -test /var/www/docker/php/schedule/schedule | grep -q 'is valid' # TODO try spatie LARAVEL-HEALTH
            interval: 5s
            timeout: 10s
            retries: 2

    webserver:
        image: nginx:1.26.0-alpine
        container_name: webserver
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            #            - ./docker/nginx/certs/:/etc/nginx/certs/
            - ./storage/logs/nginx/:/var/log/nginx/
        ports:
            - 80:80
        #            - 443:443
        networks:
            - webserver-network
        healthcheck:
            test: curl -s http://localhost/up >/dev/null || exit 1
            interval: 5s
            timeout: 10s
            retries: 20

    redis:
        image: redis:7.2.4-alpine
        restart: unless-stopped
        container_name: redis
        command:
            - 'redis-server'
            - '--requirepass ${REDIS_PASSWORD}'
        volumes:
            - redis_data:/data
        networks:
            - redis-network
        healthcheck:
            test: redis-cli ping
            interval: 5s
            timeout: 10s
            retries: 20

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - webserver-network

volumes:
    db_data:
        driver: local
        name: db_data
    redis_data:
        driver: local
        name: redis_data
    app_composer_data:
        driver: local
        name: app_composer_data
    app_npm_data:
        driver: local
        name: app_npm_data

networks:
    db-network:
        driver: bridge
        name: db-network
    webserver-network:
        driver: bridge
        name: webserver-network
    redis-network:
        driver: bridge
        name: redis-network
